# This file only executes when the 'dev' profile is active
# Show, Format, and Color-Code SQL commands
# TURN THIS OFF: It bypasses the logger and cannot be color-coded
spring.jpa.show-sql=false

# Route Hibernate SQL through Spring's logger instead
logging.level.org.hibernate.SQL=DEBUG

# Log the actual parameter values instead of "?" placeholders
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Format the SQL into structured multi-line statements
spring.jpa.properties.hibernate.format_sql=true

# Force Spring Boot to use ANSI colors in your terminal console
spring.output.ansi.enabled=ALWAYS
