# Core Application Configuration
spring.application.name=name-app

# 1. Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/user_profile_db
spring.datasource.username=devuser
spring.datasource.password=devpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Hibernate / JPA Settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

# 3. Show SQL commands in the console (Great for learning!)
spring.jpa.show-sql=true

